language: node_js
sudo: false

node_js:
- '6'

os:
- linux

## Disable because it seems to be often slow (and sometimes errored)
## on Travis CI
# - osx

matrix:
  fast_finish: true
  exclude:
  - os: osx
    node_js: '4'

script:
- npm test

branches:
  only:
  - master
  - /^greenkeeper/.*$/

### cache node_modules/ dir between builds on travis
# Issues with node 4
#cache:
#  directories:
#    - node_modules
